standalone_tags:
  []
tag_bundles:
  [
    {
      name: 'calibration_board',
      layout:
        [
          {id: 250, size: 0.024, x: -0.165, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 221, size: 0.024, x: 0.165, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 251, size: 0.024, x: -0.135, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 220, size: 0.024, x: 0.135, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 252, size: 0.024, x: -0.105, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 219, size: 0.024, x: 0.105, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 253, size: 0.024, x: -0.075, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 218, size: 0.024, x: 0.075, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 254, size: 0.024, x: -0.045, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 217, size: 0.024, x: 0.045, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 255, size: 0.024, x: -0.015, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 216, size: 0.024, x: 0.015, y: 0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 242, size: 0.024, x: -0.165, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 229, size: 0.024, x: 0.165, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 241, size: 0.024, x: -0.135, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 230, size: 0.024, x: 0.135, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 240, size: 0.024, x: -0.105, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 231, size: 0.024, x: 0.105, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 239, size: 0.024, x: -0.075, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 232, size: 0.024, x: 0.075, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 238, size: 0.024, x: -0.045, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 233, size: 0.024, x: 0.045, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 237, size: 0.024, x: -0.015, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 234, size: 0.024, x: 0.015, y: -0.120, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 249, size: 0.024, x: -0.165, y: 0.090, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 248, size: 0.024, x: -0.165, y: 0.060, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 247, size: 0.024, x: -0.165, y: 0.030, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 246, size: 0.024, x: -0.165, y: 0.0, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 245, size: 0.024, x: -0.165, y: -0.030, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 244, size: 0.024, x: -0.165, y: -0.060, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 243, size: 0.024, x: -0.165, y: -0.090, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 222, size: 0.024, x: 0.165, y: 0.090, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 223, size: 0.024, x: 0.165, y: 0.060, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 224, size: 0.024, x: 0.165, y: 0.030, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 225, size: 0.024, x: 0.165, y: 0.0, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 226, size: 0.024, x: 0.165, y: -0.030, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 227, size: 0.024, x: 0.165, y: -0.060, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 228, size: 0.024, x: 0.165, y: -0.090, z:  0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
        ]
    }
  ]