standalone_tags:
  [
    {id: 216, size: 0.024},
    {id: 217, size: 0.024},
    {id: 218, size: 0.024},
    {id: 219, size: 0.024},
    {id: 220, size: 0.024},
    {id: 221, size: 0.024},
    {id: 222, size: 0.024},
    {id: 223, size: 0.024},
    {id: 224, size: 0.024},
    {id: 225, size: 0.024},
    {id: 226, size: 0.024},
    {id: 227, size: 0.024},
    {id: 228, size: 0.024},
    {id: 229, size: 0.024},
    {id: 230, size: 0.024},
    {id: 231, size: 0.024},
    {id: 232, size: 0.024},
    {id: 233, size: 0.024},
    {id: 234, size: 0.024},
    {id: 235, size: 0.024},
    {id: 236, size: 0.024},
    {id: 237, size: 0.024},
    {id: 238, size: 0.024},
    {id: 239, size: 0.024},
    {id: 240, size: 0.024},
    {id: 241, size: 0.024},
    {id: 242, size: 0.024},
    {id: 243, size: 0.024},
    {id: 244, size: 0.024},
    {id: 245, size: 0.024},
    {id: 246, size: 0.024},
    {id: 247, size: 0.024},
    {id: 248, size: 0.024},
    {id: 249, size: 0.024},
    {id: 250, size: 0.024},
    {id: 251, size: 0.024},
    {id: 252, size: 0.024},
    {id: 253, size: 0.024},
    {id: 254, size: 0.024},
    {id: 255, size: 0.024}
  ]
tag_bundles:
  [
  ]
